const SQUARE_DATA = {
    'Go': {type: 'go', title: 'Go', next: 'Mediterranean'},
    'Mediterranean': {type: 'property', title: 'Mediterranean', next: 'Community Chest 1'},
    'Community Chest 1': {type: 'community-chest', title: 'Community Chest 1', next: 'Baltic'},
    'Baltic': {type: 'property', title: 'Baltic', next: 'Income Tax'},
    'Income Tax': {type: 'income-tax', title: 'Income Tax', next: 'Reading Railroad'},
    'Reading Railroad': {type: 'railroad', title: 'Reading Railroad', next: 'Oriental'},
    'Oriental': {type: 'property', title: 'Oriental', next: 'Chance 1'},
    'Chance 1': {type: 'chance', title: 'Chance 1', next: 'Vermont'},
    'Vermont': {type: 'property', title: 'Vermont', next: 'Connecticut'},
    'Connecticut': {type: 'property', title: 'Connecticut', next: 'Jail'},
    'Jail': {type: 'jail', title: 'Jail', next: 'St Charles'},
    'St Charles': {type: 'property', title: 'St Charles', next: 'Electric Company'},
    'Electric Company': {type: 'utility', title: 'Electric Company', next: 'States'},
    'States': {type: 'property', title: 'States', next: 'Virginia'},
    'Virginia': {type: 'property', title: 'Virginia', next: 'Pennsylvania Railroad'},
    'Pennsylvania Railroad': {type: 'railroad', title: 'Pennsylvania Railroad', next: 'St James'},
    'St James': {type: 'property', title: 'St James', next: 'Community Chest 2'},
    'Community Chest 2': {type: 'community-chest', title: 'Community Chest 2', next: 'Tennessee'},
    'Tennessee': {type: 'property', title: 'Tennessee', next: 'New York'},
    'New York': {type: 'property', title: 'New York', next: 'Parking'},
    'Parking': {type: 'parking', title: 'Parking', next: 'Kentucky'},
    'Kentucky': {type: 'property', title: 'Kentucky', next: 'Chance 2'},
    'Chance 2': {type: 'chance', title: 'Chance 2', next: 'Indiana'},
    'Indiana': {type: 'property', title: 'Indiana', next: 'Illinois'},
    'Illinois': {type: 'property', title: 'Illinois', next: 'B&O Railroad'},
    'B&O Railroad': {type: 'property', title: 'B&O Railroad', next: 'Atlantic'},
    'Atlantic': {type: 'property', title: 'Atlantic', next: 'Ventnor'},
    'Ventnor': {type: 'property', title: 'Ventnor', next: 'Water Works'},
    'Water Works': {type: 'utility', title: 'Water Works', next: 'Marvin Gardens'},
    'Marvin Gardens': {type: 'property', title: 'Marvin Gardens', next: 'Go To Jail'},
    'Go To Jail': {type: 'go-to-jail', title: 'Go To Jail', next: 'Pacific'},
    'Pacific': {type: 'property', title: 'Pacific', next: 'North Carolina'},
    'North Carolina': {type: 'property', title: 'North Carolina', next: 'Community Chest 3'},
    'Community Chest 3': {type: 'community-chest', title: 'Community Chest 3', next: 'Pennsylvania'},
    'Pennsylvania': {type: 'property', title: 'Pennsylvania', next: 'Short Line Railroad'},
    'Short Line Railroad': {type: 'railroad', title: 'Short Line Railroad', next: 'Chance 3'},
    'Chance 3': {type: 'chance', title: 'Chance 3', next: 'Park Place'},
    'Park Place': {type: 'property', title: 'Park Place', next: 'Luxury Tax'},
    'Luxury Tax': {type: 'luxury-tax', title: 'Luxury Tax', next: 'Boardwalk'},
    'Boardwalk': {type: 'property', title: 'Boardwalk', next: 'Go'}
};